### ISSUE TITLE
hexatridecimal

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript-integers#21]
Porting the JS equivalent of:

```js
var uid = n.toString(36)
```

Currently what's required is either `unsafeCoerce 36` or:

```purs
let hexatridecimal = maybe hexadecimal (radix 36)
let uid = toStringAs hexatridecimal n
```

I don't think the trouble is lacking `Radix 36` as much as `radix` returns `Maybe` instead of `clamp`ing.

**Comment by paf31** [comment]
Sorry, could you give more details? What's the problem you'd like to solve here?

**Comment by texastoland** [comment]
Porting the JS equivalent of:

```js
var uid = n.toString(36)
```

Currently what's required is either `unsafeCoerce 36` or:

```purs
let uid = toStringAs (maybe hexadecimal (radix 36)) n
```

I don't think the problem is really lacking `Radix 36` but that `radix` returns `Maybe` instead of `clamp`ing.

**Comment by paf31** [comment]
Ah, I see, thanks.

**Comment by paf31** [comment]
I think we could reasonably add an `unsafeRadix` function as well as a `base36 :: Radix` value.

**Comment by garyb** [comment]
I think `Maybe` is always preferrable to clamping because it makes you think about how you want to handle the exceptional circumstance - maybe you do want it to fail rather than clamping, or maybe you want it to choose some other arbitrary radix. Clamping makes the failure silent and therefore something you have to go and look up if things aren't behaving as you expected later.

So :+1: for adding a `base36` radix value.

**Comment by texastoland** [comment]
> So 👍 for adding a base36 radix value. 😄

Do you prefer that over `hexatridecimal`? I only suggested it for consistency.

Also I'm using `toStringAs` with `Number`. Right now I'm just using `unsafeCoerce`. Would it be worth PRing somewhere as well?

**Comment by sharkdp** [comment]
> > So  for adding a base36 radix value. 
>
> Do you prefer that over hexatridecimal? I only suggested it for consistency.

I prefer base36. I think its easier to parse (by a human).
 
> Also I'm using toStringAs with Number. Right now I'm just using unsafeCoerce. Would it be worth PRing somewhere as well?

@hdgarrood also suggested to implement a `Number` version in #17. I never wanted to use floating point values in a non-decimal system so I finally decided to just implement this for `Int` here.

If you only want to convert an integer `Number` to an `Int`, I'd go with `round` or `floor` instead of `unsafeCoerce`.

**Comment by garyb** [comment]
Yeah, I prefer "base36" too as "hexatridecimal" is not a common name like the others. I misread it as just "hexadecimal" at first too :wink:

**Comment by texastoland** [comment]
> If you only want to convert an integer `Number` to an `Int`, I'd go with `round` or `floor` instead of `unsafeCoerce`.

Originally I was using it with integers too big too be represented by `Int` (for UIDs hence base 36). I switched to a much simpler version that just takes the suffix from a floating point. `unsafeCoerce` is the only solution in either case outside of a separate function:

```purs
mkUID = do
  randomOrZero <- random
  randomOffset <- random
  let probablyNotZero = randomOrZero + randomOffset
  let base36 = toStringAs (unsafeCoerce 36) (unsafeCoerce probablyNotZero)
  pure (drop 2 base36)
```
