### ISSUE TITLE
Provide a clamping Radix constructor

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-integers#46]
I'd quite like to have a function `Int -> Radix` which avoids failure by clamping to the valid range (so e.g. passing 0 would give you a radix of 2, and passing 100 would give you a radix of 36). @garyb already said that he didn't want this in #21, but I think it does kind of suck to have to do eg

```patch
 x :: String -> Maybe Int
-x = readInt 2 
+x = fromStringAs (unsafeRadix 2)
+  where
+  unsafeRadix n = unsafePartial fromJust $ radix n
```

when upgrading from 0.13.x. I think the radix is probably known at compile time in most cases. We already have eg `unsafeRegex` as well as the clamping formatters in `numbers`, so I think there's prior art for this too.

**Comment by hdgarrood** [comment]
Oh, hm, since we already export `Radix` values for all the common ones maybe we don't really need this after all?

**Comment by JordanMartinez** [comment]
Probably not. Should this be closed then?

**Comment by hdgarrood** [comment]
Works for me.

**Comment by garyb** [comment]
I've probably softened my position on that a bit since the original issue - the amount of unsafe regexes I've written since then suggests there is a very real use case for non-failing versions of these things sometimes. Ideally we could use a way of saying they should only be allowed to evaluate at definition-time though :wink:.
